# threat_engine/reasons.py

class Reason:
    POST_EXPLOITATION_INDICATORS = "POST_EXPLOITATION_INDICATORS"
    POST_EXPLOITATION_BEHAVIOR = "POST_EXPLOITATION_BEHAVIOR"
    MULTI_STAGE_ATTACK = "MULTI_STAGE_ATTACK"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    MULTI_NODE_OBSERVATION = "MULTI_NODE_OBSERVATION"
    ESCALATED_MULTI_NODE = "ESCALATED_MULTI_NODE"
    ESCALATED_DISTRIBUTED_ATTACK = "ESCALATED_DISTRIBUTED_ATTACK"

    INSUFFICIENT_CONFIDENCE = "insufficient_confidence"
    SINGLE_NODE_ONLY = "single_node_only"
    LOW_SCENARIO_VOLUME = "low_scenario_volume"
    INSUFFICIENT_EVIDENCE = "insufficient_evidence"

    HIGH_SEVERITY_SINGLE_NODE = "HIGH_SEVERITY_SINGLE_NODE"
    HIGH_SEVERITY_EXPLOIT = "HIGH_SEVERITY_EXPLOIT"
    REPEATED_LOW_CONFIDENCE_ACTIVITY = "REPEATED_LOW_CONFIDENCE_ACTIVITY"
