# threat_engine/reasons.py

class Reason:
    POST_EXPLOITATION_INDICATORS = "POST_EXPLOITATION_INDICATORS"
    POST_EXPLOITATION_BEHAVIOR = "POST_EXPLOITATION_BEHAVIOR"
    MULTI_STAGE_ATTACK = "MULTI_STAGE_ATTACK"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    MULTI_NODE_OBSERVATION = "MULTI_NODE_OBSERVATION"
    ESCALATED_MULTI_NODE = "ESCALATED_MULTI_NODE"
    ESCALATED_DISTRIBUTED_ATTACK = "ESCALATED_DISTRIBUTED_ATTACK"

    INSUFFICIENT_CONFIDENCE = "INSUFFICIENT_CONFIDENCE"
    SINGLE_NODE_ONLY = "SINGLE_NODE_ONLY"
    LOW_SCENARIO_VOLUME = "LOW_SCENARIO_VOLUME"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"

    REPUTATION_ESCALATION_WARNING = "REPUTATION_ESCALATION_WARNING"
    REPUTATION_ESCALATION_CRITICAL = "REPUTATION_ESCALATION_CRITICAL"

    HIGH_SEVERITY_SINGLE_NODE = "HIGH_SEVERITY_SINGLE_NODE"
    HIGH_SEVERITY_EXPLOIT = "HIGH_SEVERITY_EXPLOIT"
    REPEATED_LOW_CONFIDENCE_ACTIVITY = "REPEATED_LOW_CONFIDENCE_ACTIVITY"

    PRESERVED_EXISTING_DECISION = "PRESERVED_EXISTING_DECISION"
